Implemented shellcheck recommendations

diff --git a/build b/build
--- a/build
+++ b/build
@@ -37,16 +37,17 @@ distro_get() {
 }
 
 recipe_item_get() {
-   local recipe=$RECIPEDIR/$1.recipe
+   local recipe="$RECIPEDIR/$1.recipe"
    local label=$2
    local item=$3
 
-   local value=$( recipe_section_get $1 $label optional | grep "^${item}=" )
+   local value
+   value=$( recipe_section_get "$1" "$label" optional | grep "^${item}=" )
    if test "$value" = "" -a "$#" = 4
    then
-      echo $4
+      echo "$4"
    else
-      echo ${value/*=/}
+      echo "${value/*=/}"
    fi
    test "$value" = "" && return 0 || return 1
 }
@@ -57,10 +58,10 @@ recipe_section_get() {
    local label=$2
    local opt=$3
 
-   test ! -f $recipe && { test "$opt" = "" && { >&2 output "Recipe $recipename ($recipe) does not exist."; return 1; } }
+   test ! -f "$recipe" && { test "$opt" = "" && { >&2 output "Recipe $recipename ($recipe) does not exist."; return 1; } }
 
-   grep "^\[$label\]" $recipe > /dev/null 2>&1  || { test "$opt" = "" &&  { >&2 output "No section $label found in recipe $recipe"; exit 1; } }
-   awk "BEGIN {found=0;} /^\[/ {found=0;} {if (found==1) { print \$0;}}; /^\[$label\]/ { found=1;}" $recipe | grep -v "^#"
+   grep "^\[$label\]" "$recipe" > /dev/null 2>&1  || { test "$opt" = "" &&  { >&2 output "No section $label found in recipe $recipe"; exit 1; } }
+   awk "BEGIN {found=0;} /^\[/ {found=0;} {if (found==1) { print \$0;}}; /^\[$label\]/ { found=1;}" "$recipe" | grep -v "^#"
 }
 
 build_require() {
@@ -72,10 +73,10 @@ build_require() {
 
    for pkg in $pkgs
    do
-      dpkg-query -s ${pkg/*@/} > /dev/null 2>&1
+      dpkg-query -s "${pkg/*@/}" > /dev/null 2>&1
       if test $? -ne 0
       then
-         test $QUIET -eq 0 && output "Package $pkg required for build, but not installed."
+         test "$QUIET" -eq 0 && output "Package $pkg required for build, but not installed."
          if test "$INSTDEP" = "yes" 
          then
             test "$pkg" = "${pkg/*@/}" && toinst="$toinst $pkg" || toinsttr="$toinsttr $pkg"
@@ -84,10 +85,10 @@ build_require() {
          fi
       fi
    done
-   test "$toinst" != "" && { sudo apt-get -qq -y install $toinst > /dev/null 2>&1 || { output "Error installing dependancies ($toinst)."; return 1 ;} }
+   test "$toinst" != "" && { sudo apt-get -qq -y install "$toinst" > /dev/null 2>&1 || { output "Error installing dependancies ($toinst)."; return 1 ;} }
    test "$toinsttr" != "" && for pkg in $toinsttr
    do
-      sudo apt-get -qq -y -t ${pkg/@*/} install ${pkg/*@/}  > /dev/null 2>&1 || { output "Error installing dependancy ($pkg)."; return 1 ; }
+      sudo apt-get -qq -y -t "${pkg/@*/}" install "${pkg/*@/}"  > /dev/null 2>&1 || { output "Error installing dependancy ($pkg)."; return 1 ; }
    done
    test $missing -eq 1 && return 1
    return 0
@@ -101,7 +102,7 @@ build_require_remove() {
    do
       list="$list ${pkg/*@/}"
    done
-   sudo apt-get -qq -y --purge remove $list > /dev/null
+   sudo apt-get -qq -y --purge remove "$list" > /dev/null
 }
 
 # ToDo: check local vars
@@ -114,23 +115,25 @@ build() {
    else
       versiondir=$B_VERSION
    fi
-   local pkgs=$( recipe_section_get $B_NAME REQUIRED opt )
-   ( test $? -eq 0 &&  build_require $pkgs ) || return 1
+   local pkgs
+   pkgs=$( recipe_section_get "$B_NAME" REQUIRED opt )
+   ( test $? -eq 0 &&  build_require "$pkgs" ) || return 1
 
    test "$B_INSTANCE" != "" && ID=${B_NAME}_${B_VERSION}-${B_INSTANCE}_${B_ARCH} || ID=${B_NAME}_${B_VERSION}_${B_ARCH}
-   B_BUILDNR=$( package_buildnr_get $ID )
-   local CMD=$( recipe_section_get $B_NAME BUILD ) || return 1
-   test $? -ne 0 && { ERR=1 output $CMD ; return 1; }
-   local TMP=$( mktemp -p $TMPDIR -d )
+   B_BUILDNR=$( package_buildnr_get "$ID" )
+   local CMD
+   CMD=$( recipe_section_get "$B_NAME" BUILD ) || return 1
+   test $? -ne 0 && { ERR=1 output "$CMD" ; return 1; }
+   local TMP
+   TMP=$( mktemp -p "$TMPDIR" -d )
    B_INSTALLDIR=$DESTDIR/$B_ARCH/$B_NAME-$versiondir
-   test $FORCE -eq 1 && rm -rf $B_INSTALLDIR
-   mkdir -p $B_INSTALLDIR
+   test "$FORCE" -eq 1 && rm -rf "$B_INSTALLDIR"
+   mkdir -p "$B_INSTALLDIR"
    # Define build environment variables and functions
    B_CACHEDIR=$CACHEDIR
-   test -d $RECIPEDIR/$B_NAME.files/B_BUILD && B_FILES=$RECIPEDIR/$B_NAME.files/B_BUILD
+   test -d "$RECIPEDIR/$B_NAME.files/B_BUILD" && B_FILES=$RECIPEDIR/$B_NAME.files/B_BUILD
    B_PKGLIST=$PKGLIST
-   # export B_VERSION B_INSTALLDIR B_ARCH B_DESTDIR B_INSTANCE B_CACHEDIR B_NAME B_BUILDNR B_PKGLIST
-   export B_VERSION B_INSTALLDIR B_ARCH B_INSTANCE B_CACHEDIR B_NAME B_BUILDNR B_FILES
+   export B_VERSION B_INSTALLDIR B_ARCH B_INSTANCE B_CACHEDIR B_NAME B_BUILDNR B_FILES B_PKGLIST
    B_GET() {
       test $# -ne 3 && { >&2 echo "Insufficient arguments to B_GET."; exit 1; }
       local method=$1
@@ -140,42 +143,42 @@ build() {
       local target=$targetdir/$fn
       case $method in
       "http")
-         if ! test -f $target
+         if ! test -f "$target"
          then
-            test -d $targetdir || mkdir -p $targetdir
+            test -d "$targetdir" || mkdir -p "$targetdir"
             echo "Http downloading files.."
-            wget -q -O $target $url || rm $target
+            wget -q -O "$target" "$url" || rm "$target"
             test $? -ne 0 && { echo "Error downloading file."; exit 1; }
          fi
-         cp $target $fn
+         cp "$target" "$fn"
       ;;
       "git")
-         if ! test -f $target
+         if ! test -f "$target"
          then
-            test -d $targetdir || mkdir -p $targetdir
+            test -d "$targetdir" || mkdir -p "$targetdir"
             mkdir /tmp/git-dl.$$
             cd /tmp/git-dl.$$
             echo "Git downloading files.."
-            git clone $url $fn
-            tar cfz $target $fn
+            git clone "$url" "$fn"
+            tar cfz "$target" "$fn"
             cd - > /dev/null
             rm -rf /tmp/git-dl.$$
          fi
-         tar xzf $target
+         tar xzf "$target"
       ;;
       "svn")  
-         if ! test -f $target
+         if ! test -f "$target"
          then
-            test -d $targetdir || mkdir -p $targetdir
+            test -d "$targetdir" || mkdir -p "$targetdir"
             mkdir /tmp/svn-dl.$$
             cd /tmp/svn-dl.$$
             echo "Subversion downloading files.."
-            svn checkout --non-interactive --trust-server-cert -q $url $fn
-            tar cfz $target $fn
+            svn checkout --non-interactive --trust-server-cert -q "$url" "$fn"
+            tar cfz "$target" "$fn"
             cd - > /dev/null
             rm -rf /tmp/git-dl.$$
          fi
-         tar xzf $target
+         tar xzf "$target"
       ;;
       *)
          echo "B_GET: unknown method $method"
@@ -192,35 +195,35 @@ build() {
       else
          local ID=${B_NAME}_${B_VERSION}_${B_ARCH}
       fi
-      grep "^$ID" $PKGLIST > /dev/null && sed -i "/^$ID/d" $PKGLIST
-      echo -e "$ID\t$B_BUILDNR" >> $PKGLIST
+      grep "^$ID" "$PKGLIST" > /dev/null && sed -i "/^$ID/d" "$PKGLIST"
+      echo -e "$ID\t$B_BUILDNR" >> "$PKGLIST"
    }
    export -f B_UPDATEPKGBLD
    B_LINKFILES() {
       local src=$1; local dst=$2
-      test -d $B_INSTALLDIR/$src || { echo "B_LINKFILES: source needs to be a directory within the B_INSTALLDIR tree."; exit 1; }
-      test -d $B_INSTALLDIR/$dst || mkdir -p $B_INSTALLDIR/$dst
+      test -d "$B_INSTALLDIR/$src" || { echo "B_LINKFILES: source needs to be a directory within the B_INSTALLDIR tree."; exit 1; }
+      test -d "$B_INSTALLDIR/$dst" || mkdir -p "$B_INSTALLDIR/$dst"
       local name
-      for name in $( ls $B_INSTALLDIR/$src | grep -v ".real$" )
+      for name in $( ls "$B_INSTALLDIR/$src" | grep -v ".real$" )
       do
-         ln -s $src/$name $B_INSTALLDIR/$dst
+         ln -s "$src/$name" "$B_INSTALLDIR/$dst"
       done
    }
    export -f B_LINKFILES
-   cd $TMP
+   cd "$TMP"
    if test "$QUIET" = "1"; then
-      bash $DEBUG -e -c "$CMD" > /dev/null 2>&1
+      bash "$DEBUG" -e -c "$CMD" > /dev/null 2>&1
    else
-      bash $DEBUG -e -c "$CMD"
+      bash "$DEBUG" -e -c "$CMD"
    fi
    result=$?
    cd - > /dev/null
-   rm -rf $TMP
-   test "$pkgs" != "" -a "$DEINSTDEP" = "yes" -a $B_NOPKGRM -eq 0 && build_require_remove "$pkgs"
-   test "$POSTBUILD" != "" -a $B_NOPKGRM -eq 0 && $POSTBUILD
+   rm -rf "$TMP"
+   test "$pkgs" != "" -a "$DEINSTDEP" = "yes" -a "$B_NOPKGRM" -eq 0 && build_require_remove "$pkgs"
+   test "$POSTBUILD" != "" -a "$B_NOPKGRM" -eq 0 && $POSTBUILD
    if test $result -ne 0
    then
-      rm -rf $B_INSTALLDIR
+      rm -rf "$B_INSTALLDIR"
       return 1
    fi
    return 0
@@ -260,15 +263,15 @@ arch_get() {
 
 package_buildnr_get() {
    local ID=$1
-   test -f $PKGLIST || touch $PKGLIST
-   local BUILDNR=$(grep "^$ID" $PKGLIST | cut -d'	' -f 2 )
+   test -f "$PKGLIST" || touch "$PKGLIST"
+   local BUILDNR
+   BUILDNR=$(grep "^$ID" "$PKGLIST" | cut -d'	' -f 2 )
    test "$BUILDNR" = "" && BUILDNR=0
-   echo $(( $BUILDNR + 1 ))
+   echo $(( BUILDNR + 1 ))
 }
 
 package_torepo() {
    local type
-   local options=""
    local pkg
    local pkgs="$*"
    local splittype
@@ -281,13 +284,13 @@ package_torepo() {
       splittype[$type]="${splittype[$type]} $pkg"
    done
 
-   cd $PKGDIR
+   cd "$PKGDIR"
    RET=0
-   for type in ${!splittype[@]}
+   for type in "${!splittype[@]}"
    do
       case "$type" in
       "deb")
-         $TODEBREPO ${splittype[$type]}
+         $TODEBREPO "${splittype[$type]}"
          test $? -ne 0 && RET=1
       ;;
       *)
@@ -319,12 +322,13 @@ package() {
    else
       ID=${version}
    fi
-   local type=$( recipe_item_get $pkg PKG type )
+   local type
+   type=$( recipe_item_get "$pkg" PKG type )
    for pkgtype in ${type/,/ }
    do
       case $pkgtype in
       "deb")
-         package_debian $pkg $version
+         package_debian "$pkg" "$version"
          return $?
       ;;
       *)
@@ -340,70 +344,79 @@ package_debian() {
    local pkg=$1
    local version=$2
 
-   local pkgready=$( recipe_item_get $pkg PKG pkgready )
+   local pkgready
+   pkgready=$( recipe_item_get "$pkg" PKG pkgready )
    local P_PKGDIR=${pkg}-${ID}
    if test "$pkgready" = ""
    then
       local P_PKGNAME=${pkg}_${ID}_${B_ARCH}
-      local P_BUILDNR=$( package_buildnr_get ${P_PKGNAME} )
-      local INFO=$(recipe_section_get $pkg DEB) || return 1
-      local TMP=$( mktemp -p $TMPDIR -d )
-      mkdir -p $TMP/DEBIAN
+      local P_BUILDNR
+      P_BUILDNR=$( package_buildnr_get "${P_PKGNAME}" )
+      local INFO
+      INFO=$(recipe_section_get "$pkg" DEB) || return 1
+      local TMP
+      TMP=$( mktemp -p "$TMPDIR" -d )
+      mkdir -p "$TMP/DEBIAN"
       local pkgversion=${version//\-/}-$P_BUILDNR
       test "$PKGPOSTFIX" != "" && INFO=$( echo "$INFO" | sed "/^Package:/ s/$/-$PKGPOSTFIX/" )
-      echo "$INFO" | sed "s/VERSION/$pkgversion/" | sed "s/ARCH/$B_ARCH/" > $TMP/DEBIAN/control
-      cd $DESTDIR/$B_ARCH/$pkg-$version
+      echo "$INFO" | sed "s/VERSION/$pkgversion/" | sed "s/ARCH/$B_ARCH/" > "$TMP/DEBIAN/control"
+      cd "$DESTDIR/$B_ARCH/$pkg-$version"
       tar pcfB - . | (cd $TMP ; tar pxfB - )
-      cd $TMP
-      if test -d $RECIPEDIR/$pkg.files/B_DEBIAN
+      cd "$TMP"
+      if test -d "$RECIPEDIR/$pkg.files/B_DEBIAN"
       then
-         ( cd $RECIPEDIR/$pkg.files/B_DEBIAN ; tar cf - . ) | tar xf -
+         ( cd "$RECIPEDIR/$pkg.files/B_DEBIAN" ; tar cf - . ) | tar xf -
       fi
       # Mark config files
       find . -path "*/etc/*" -type f | sed "s/^\.//" > DEBIAN/conffiles
-      local configfiles=$( recipe_item_get $pkg PKG configfiles )
-      test "$configfiles" != "" && { echo $configfiles | tr ' ' '\n' >> DEBIAN/conffiles; }
-      cd $TMPDIR
-      fakeroot dpkg --build $TMP . > $TMP.buildoutput
+      local configfiles
+      configfiles=$( recipe_item_get "$pkg" PKG configfiles )
+      test "$configfiles" != "" && { echo "$configfiles" | tr ' ' '\n' >> DEBIAN/conffiles; }
+      cd "$TMPDIR"
+      fakeroot dpkg --build "$TMP" . > "$TMP.buildoutput"
       result=$?
-      local pkgfile=$( cat $TMP.buildoutput | cut -d \' -f 4 )
-      pkgfile=${pkgfile/*\//}
-      rm -rf $TMP $TMP.buildoutput
+      local pkgfile
+      pkgfile=$( cut -d \' -f 4 < "$TMP.buildoutput" )
+      pkgfile="${pkgfile/*\//}"
+      rm -rf "$TMP" "$TMP.buildoutput"
       if test $result -ne 0
       then
          ERR=1 output "Error while building package."
          return 1
       fi
-      grep "^${P_PKGNAME}_${B_ARCH}" $PKGLIST > /dev/null && sed -i "/^${P_PKGNAME}_${B_ARCH}/d" $PKGLIST
-      echo -e "${P_PKGNAME}_${B_ARCH}\t$P_BUILDNR" >> $PKGLIST
-      mv $TMPDIR/$pkgfile $PKGDIR
+      grep "^${P_PKGNAME}_${B_ARCH}" "$PKGLIST" > /dev/null && sed -i "/^${P_PKGNAME}_${B_ARCH}/d" "$PKGLIST"
+      echo -e "${P_PKGNAME}_${B_ARCH}\t$P_BUILDNR" >> "$PKGLIST"
+      mv "$TMPDIR/$pkgfile" "$PKGDIR"
    else
-      if test "$( echo $DESTDIR/$B_ARCH/${P_PKGDIR}/*.deb )" = "$DESTDIR/$B_ARCH/${P_PKGDIR}/*.deb"
+      if test "$( echo "$DESTDIR/$B_ARCH/${P_PKGDIR}"/*.deb )" = "$DESTDIR/$B_ARCH/${P_PKGDIR}/*.deb"
       then
          ERR=1 output "Recipe indicates package should be in build dir, but it isn't."
          return 1
       else
          file="$DESTDIR/$B_ARCH/${P_PKGDIR}/*.deb"
-         cp $file $PKGDIR
-         pkgfile=$(basename $DESTDIR/$B_ARCH/${P_PKGDIR}/*.deb)
+         cp "$file" "$PKGDIR"
+         pkgfile=$(basename "$DESTDIR/$B_ARCH/${P_PKGDIR}"/*.deb)
       fi
    fi
-   echo $pkgfile
+   echo "$pkgfile"
 }
 
 version_get() {
    local pkg=$1
    local CMD
 
-   export B_ARCH=$( arch_get )
-   export B_NAME=$1
+   B_ARCH=$( arch_get )
+   export B_ARCH
+   B_NAME=$1
+   export B_NAME
    B_GITVER() {
-      git ls-remote --tags $1 | grep -v '{}' | cut -d '/' -f 3  | sed "s/^v//" | grep -v -e preview -e rc -e a -e b | sort -t. -k 1,1n -k 2,2n -k 3,3n -k 4,4n | tail -1
+      git ls-remote --tags "$1" | grep -v '{}' | cut -d '/' -f 3  | sed "s/^v//" | grep -v -e preview -e rc -e a -e b | sort -t. -k 1,1n -k 2,2n -k 3,3n -k 4,4n | tail -1
    }
    export -f B_GITVER
-   CMD=$( recipe_section_get $pkg VERSION )
-   test $? -ne 0 && { output $CMD ; return 1; }
-   local ver=$( bash $DEBUG -e -c "$CMD" 2>/dev/null )
+   CMD=$( recipe_section_get "$pkg VERSION" )
+   test $? -ne 0 && { output "$CMD" ; return 1; }
+   local ver
+   ver=$( bash "$DEBUG" -e -c "$CMD" 2>/dev/null )
    test $? -ne 0 && { >&2 output "Error while running version command for $pkg." ; return 1 ; }
    test "$ver" = "" && { >&2 output "Version command for $pkg returned no output." ; return 1 ; }
    echo $ver
@@ -413,7 +426,7 @@ version_get() {
 # ToDo: check local vars
 # ToDo: create better option vars
 parse_options() {
-   FORCE=0 ; QUIET=0 ; DEBUG= ; PKGS= ; FORCEVERSION=
+   FORCE=0 ; QUIET=0 ; DEBUG= ; FORCEVERSION=
    DO_CHECK=0; DO_BUILD=0; DO_PACKAGE=0; DO_REPO=0; B_NOPKGRM=0
    while test "$1" != ""
    do
@@ -455,7 +468,7 @@ parse_options() {
          DEBUG=-x
       ;;
       "-q")
-         QUIET=$(( $QUIET +1 ))
+         QUIET=$(( QUIET +1 ))
       ;;
       "-f")
          FORCE=1
@@ -490,15 +503,15 @@ sanity_check() {
    local name
    for name in $( require_software)
    do
-      if ! which $name > /dev/null 2>&1
+      if ! which "$name" > /dev/null 2>&1
       then
          missing="$missing $name"
       fi
    done
    test "$missing" != "" && { output "Missing required software to run script:$missing" ; exit 1;}
    test "$PKGDIR" = ""  && { ERR=1 output "PKGDIR not defined"; exit 1;}
-   test -d $PKGDIR || { ERR=1 output "PKGDIR $PKGDIR does not exist, aborting."; exit 1; }
-   test -d $TMPDIR || { ERR=1 output "TMPDIR $TMPDIR does not exist, aborting."; exit 1; }
+   test -d "$PKGDIR" || { ERR=1 output "PKGDIR $PKGDIR does not exist, aborting."; exit 1; }
+   test -d "$TMPDIR" || { ERR=1 output "TMPDIR $TMPDIR does not exist, aborting."; exit 1; }
 }
 
 output() {
@@ -517,7 +530,7 @@ check_version_built() {
    if test "$FORCEVERSION" != ""; then
       version=$FORCEVERSION
    else
-      version=$( version_get $pkg ) || return 2
+      version=$( version_get "$pkg" ) || return 2
    fi
    test -d "$DESTDIR/$B_ARCH/$pkg-$version" && { echo "$version" ; RET=1 ;} || echo "$version"
    return $RET
@@ -529,11 +542,10 @@ main() {
    QUIET=0
    local i
    local retval=0
-   declare -A packages_torepo
 
    # Set defaults
-   DESTDIR=~/build CACHEDIR=~/cache TMPDIR=~/temp BASEDIR=/opt 
-   REDIPEDIR=~/recipes PKGLIST=$RECIPEDIR/pkglist PKGDIR=~/packages
+   DESTDIR=~/build CACHEDIR=~/cache TMPDIR=~/temp
+   RECIPEDIR=~/recipes PKGLIST=$RECIPEDIR/pkglist PKGDIR=~/packages
    INSTDEP=yes DEINSTDEP=yes
    test -f ~/.buildrc && . ~/.buildrc || { echo "No configuration file found."; exit 1;}
 
@@ -546,10 +558,9 @@ main() {
 
    if test $DO_CHECK -ne 0; then
       # Get current version and check if already built
-      check_found=0
-      for i in ${!work_recipes[@]}
+      for i in "${!work_recipes[@]}"
       do
-         work_version[$i]=$( check_version_built ${work_recipes[$i]} )
+         work_version[$i]=$( check_version_built "${work_recipes[$i]}" )
          work_built[$i]=$?
          test $DO_CHECK -eq 1 -o $DO_BUILD -eq 1 -a $FORCE -eq 0 && { test ${work_built[$i]} -eq 1 && output "${work_recipes[$i]} ${work_version[$i]} (already built)"; }
          test $DO_CHECK -eq 1 -o $DO_PACKAGE -ne 0 && { test ${work_built[$1]} -eq 0 && output "${work_recipes[$i]} ${work_version[$i]} (not built)"; }
@@ -558,11 +569,11 @@ main() {
 
    if test $DO_BUILD -ne 0; then
       # If not built or forced, then build
-      for i in ${!work_recipes[@]}
+      for i in "${!work_recipes[@]}"
       do
-         if test ${work_built[$i]} -eq 0 -o $FORCE -eq 1
+         if test "${work_built[$i]}" -eq 0 -o "$FORCE" -eq 1
          then
-            build ${work_recipes[$i]} ${work_version[$i]}
+            build "${work_recipes[$i]}" "${work_version[$i]}"
             test $? -eq 1 && { output -f "${work_recipes[$i]} ${work_version[$i]} (build failed)"; work_build[$i]=0; retval=1; } || { work_build[$i]=1; output -f "${work_recipes[$i]} ${work_version[$i]} (build succeeded)"; }
          fi
       done
@@ -570,7 +581,7 @@ main() {
 
    if test $DO_PACKAGE -ne 0; then
       # if no build action and version built, package. if build action successful, build.
-      for i in ${!work_recipes[@]}
+      for i in "${!work_recipes[@]}"
       do
          b=0
          test $DO_BUILD -eq 0 -a ${work_built[$i]} = 1 && b=1
