Multiple large updates

diff --git a/build b/build
--- a/build
+++ b/build
@@ -23,7 +23,7 @@
 #     along with Build.  If not, see <http://www.gnu.org/licenses/>.
 
 require_software() {
-   echo awk grep git
+   echo awk grep git wget fakeroot
 }
 
 distro_get() {
@@ -37,45 +37,54 @@ distro_get() {
 }
 
 recipe_section_get() {
-   local recipe=$1
+   local recipe=$RECIPEDIR/$1.recipe
    local label=$2
    local opt=$3
 
-   test ! -f $recipe && { test "$opt" = "" && { >&2 echo "Recipe $recipe does not exist."; exit 1; } }
+   test ! -f $recipe && { test "$opt" = "" && { >&2 output "Recipe $recipe does not exist."; exit 1; } }
 
-   grep "^\[$label\]" $recipe > /dev/null 2>&1  || { test "$opt" = "" &&  { >&2 echo "No section $label found in recipe $recipe"; exit 1; } }
-   awk "BEGIN {found=0;} /^\[/ {found=0;} {if (found==1) { print \$0;}}; /\[$label\]/ { found=1;}" $recipe
+   grep "^\[$label\]" $recipe > /dev/null 2>&1  || { test "$opt" = "" &&  { >&2 output "No section $label found in recipe $recipe"; exit 1; } }
+   awk "BEGIN {found=0;} /^\[/ {found=0;} {if (found==1) { print \$0;}}; /^\[$label\]/ { found=1;}" $recipe
 }
 
 build_require() {
-   pkgs=$*
-   missing=0
-   toinst=""
+   local pkgs=$*
+   local missing=0
+   local toinst=""
+   local toinsttr=""
+   local pkg
 
    for pkg in $pkgs
    do
-      #dpkg-query -W -f='${Status}\n' $pkg > /dev/null 2>&1
-      dpkg-query -s $pkg > /dev/null 2>&1
+      dpkg-query -s ${pkg/*@/} > /dev/null 2>&1
       if test $? -ne 0
       then
-         test QUIET -eq 0 && echo "Package $pkg required for build, but not installed."
+         test $QUIET -eq 0 && output "Package $pkg required for build, but not installed."
          if test "$INSTDEP" = "yes" 
          then
-            toinst="$toinst $pkg"
+            test "$pkg" = "${pkg/*@/}" && toinst="$toinst $pkg" || toinsttr="$toinsttr $pkg"
          else
             missing=1
          fi
       fi
    done
-   if test "$toinst" != "" 
-   then
-      sudo apt-get -qq -y install $toinst > /dev/null || { echo "Error installing dependancies ($toinst)."; exit 1 ;}
-   fi
-   test $missing -eq 1 && exit 1
+   test "$toinst" != "" && { sudo apt-get -qq -y install $toinst > /dev/null 2>&1 || { output "Error installing dependancies ($toinst)."; return 1 ;} }
+   test "$toinsttr" != "" && for pkg in $toinsttr
+   do
+      sudo apt-get -qq -y -t ${pkg/@*/} install ${pkg/*@/}  > /dev/null 2>&1 || { output "Error installing dependancy ($pkg)."; return 1 ; }
+   done
+   test $missing -eq 1 && return 1
 }
 
 build_require_remove() {
-   sudo apt-get -qq -y --purge remove $pkgs > /dev/null
+   local pkgs="$1"
+   local pkg
+   for pkg in $pkgs
+   do
+      list="$list ${pkg/*@/}"
+   done
+   sudo apt-get -qq -y --purge remove $list > /dev/null
+   sudo apt-get -qq -y --purge autoremove > /dev/null
 }
 
 build() {
@@ -87,15 +96,15 @@ build() {
    else
       versiondir=$B_VERSION
    fi
-   local pkgs=$( recipe_section_get $RECIPE REQUIRED opt ) || exit 1
-   test $? -eq 0 && build_require $pkgs
+   local pkgs=$( recipe_section_get $B_NAME REQUIRED opt )
+   test $? -eq 0 &&  build_require $pkgs
 
    test "$B_INSTANCE" != "" && ID=${B_NAME}_${B_VERSION}-${B_INSTANCE}_${B_ARCH} || ID=${B_NAME}_${B_VERSION}_${B_ARCH}
    B_BUILDNR=$( package_buildnr_get $ID )
-   local CMD=$( recipe_section_get $RECIPE BUILD ) || exit 1
-   test $? -ne 0 && { echo $CMD ; exit 1; }
+   local CMD=$( recipe_section_get $B_NAME BUILD ) || return 1
+   test $? -ne 0 && { output $CMD ; return 1; }
    local TMP=$( mktemp -p $TMPDIR -d )
-   B_INSTALLDIR=$DESTDIR/$B_ARCH/$NAME-$versiondir
+   B_INSTALLDIR=$DESTDIR/$B_ARCH/$B_NAME-$versiondir
    test $FORCE -eq 1 && rm -rf $B_INSTALLDIR
    mkdir -p $B_INSTALLDIR
    # Define build environment variables and functions
@@ -116,22 +125,21 @@ build() {
          if ! test -f $target
          then
             test -d $targetdir || mkdir -p $targetdir
-            wget -O $target $url || rm $target
+            echo "Http downloading files.."
+            wget -q -O $target $url || rm $target
          fi
          cp $target $fn
       ;;
       "git")
-         #local commit=$( git ls-remote $url HEAD | cut -f 1)
-         #test "$commit" = "" && commit=$( git ls-remote $url refs/heads/master | cut -f 1)
-         #test "$commit" = "" && { echo "Unable to determine last GIT commit id. Aborting."; exit 1; }
          if ! test -f $target
          then
             test -d $targetdir || mkdir -p $targetdir
             mkdir /tmp/git-dl.$$
             cd /tmp/git-dl.$$
+            echo "Git downloading files.."
             git clone $url $fn
             tar cfz $target $fn
-            cd -
+            cd - > /dev/null
             rm -rf /tmp/git-dl.$$
          fi
          tar xzf $target
@@ -152,20 +160,21 @@ build() {
    }
    export -f B_UPDATEPKGBLD
 
-   echo "Building $NAME version $B_VERSION."
+   output "Building $B_NAME version $B_VERSION."
    cd $TMP
    test "$QUIET" = "1" && bash $DEBUG -e -c "$CMD" > /dev/null 2>&1 || bash $DEBUG -e -c "$CMD"
    result=$?
-   cd -
+   cd - > /dev/null
    rm -rf $TMP
+   test "$pkgs" != "" -a "$DEINSTDEP" = "yes" && build_require_remove "$pkgs"
    if test $result -ne 0
    then
-      echo "Build of $NAME failed."
+      output "Build of $B_NAME failed."
       rm -rf $B_INSTALLDIR
-      exit 1
+      return 1
+   else
+      output "Build complete."
    fi
-   echo "Build complete."
-   test "$pkgs" != "" -a "$DEINSTDEP" = "yes" && build_require_remove $pkgs
 }
 
 usage() {
@@ -207,32 +216,60 @@ package_buildnr_get() {
 }
 
 package_torepo() {
-   type=$1
+   packages_torepo[$1]="${packages_torepo[$1]} $2"
+}
+
+package_torepo_copy() {
+   local type
+   local options=""
+
+   test $QUIET -eq 1 && options="$options -q"
+
+   for type in ${!packages_torepo[@]}
+   do
+      case "$type" in
+      "deb")
+         $TODEBREPO $options ${packages_torepo[$type]}
+      ;;
+      *)
+         output "Copy to repository not implemented for type $type"
+         return 1
+      ;;
+      esac
+   done
+}
+
+
+package_torepo_old() {
+   local type=$1
    shift
-   pkgname=$*
+   local pkgname=$*
    case "$type" in
    "deb")
-      $TODEBREPO $pkgname
+      test $QUIET -ne 1 && $TODEBREPO $pkgname || $TODEBREPO -q $pkgname
    ;;
    *)
-      echo "Copy to repository not implemented for type $type"
-      exit 1
+      output "Copy to repository not implemented for type $type"
+      return 1
    ;;
    esac
 }
 
 package() {
-   test "$PKGDIR" = "" && { echo "PGKDIR not defined, aborting."; exit 1; }
-   test -d $PKGDIR || { echo "PKGDIR $PKGDIR does not exist, aborting."; exit 1; }
-   version=$( version_get ) || exit 1
-   test "$FORCEVERSION" != "" && version=$FORCEVERSION
+   test "$PKGDIR" = "" && { output "PGKDIR not defined, aborting."; return 1; }
+   test -d $PKGDIR || { output "PKGDIR $PKGDIR does not exist, aborting."; return 1; }
+
+   local pkg=$1
+
+   local version=$( version_get $pkg ) || return 1
+   test "$FORCEVERSION" != "" && local version=$FORCEVERSION
    if test "$B_INSTANCE" != ""
    then
-      ID=$NAME-$version-$B_INSTANCE
+      ID=$pkg-$version-$B_INSTANCE
    else
-      ID=$NAME-$version
+      ID=$pkg-$version
    fi
-   test ! -d "$DESTDIR/$B_ARCH/$ID" && { >&2 echo "Version $version of $NAME is not available for packaging." ; exit 1; }
+   test ! -d "$DESTDIR/$B_ARCH/$ID" && { >&2 output "Version $version of $pkg is not available for packaging." ; return 1; }
 
    if test "$B_INSTANCE" != ""
    then
@@ -240,18 +277,18 @@ package() {
    else
       ID=${version}
    fi
-   P_PKGNAME=${NAME}_${ID}_${B_ARCH}
-   P_PKGDIR=${NAME}-${ID}
+   P_PKGNAME=${pkg}_${ID}_${B_ARCH}
+   P_PKGDIR=${pkg}-${ID}
    P_BUILDNR=$( package_buildnr_get ${P_PKGNAME} )
-   eval $( recipe_section_get $RECIPE PKG ) || exit 1
+   eval $( recipe_section_get $pkg PKG ) || return 1
    for pkgtype in ${type/,/ }
    do
       case $pkgtype in
       "deb")
-         package_debian
+         package_debian $pkg
       ;;
       *)
-         echo "Unknown package type ($pkgtype)."
+         output "Unknown package type ($pkgtype)."
          exit 1
       ;;
       esac
@@ -259,24 +296,27 @@ package() {
 }
 
 package_debian() {
+   local pkg=$1
    # Do we need to build the package?
    if test "$pkgready" = ""
    then
-      INFO=$(recipe_section_get $RECIPE DEB) || exit 1
-      test $? -ne 0 && { echo $INFO ; exit 1; }
+      output "Building debian package..."
+      INFO=$(recipe_section_get $pkg DEB) || return 1
+      test $? -ne 0 && { output $INFO ; return 1; }
       TMP=$( mktemp -p $TMPDIR -d )
       mkdir -p $TMP/DEBIAN
       pkgversion=${version//\-/}-$P_BUILDNR
+      test "$PKGPOSTFIX" != "" && INFO=$( echo "$INFO" | sed "/^Package:/ s/$/-$PKGPOSTFIX/" )
       echo "$INFO" | sed "s/VERSION/$pkgversion/" | sed "s/ARCH/$B_ARCH/" > $TMP/DEBIAN/control
-      cd $DESTDIR/$B_ARCH/$NAME-$version
+      cd $DESTDIR/$B_ARCH/$pkg-$version
       tar pcfB - . | (cd $TMP ; tar pxfB - )
       cd - > /dev/null
       cd $TMP
-      find . -path "*/etc/*" -type f | sed "s/^\.//" > DEBIAN/conffiles
-      if test -d $RECIPEDIR/$NAME.files/B_DEBIAN
+      if test -d $RECIPEDIR/$pkg.files/B_DEBIAN
       then
-         ( cd $RECIPEDIR/$NAME.files/B_DEBIAN ; tar cf - . ) | tar xf -
+         ( cd $RECIPEDIR/$pkg.files/B_DEBIAN ; tar cf - . ) | tar xf -
       fi
+      find . -path "*/etc/*" -type f | sed "s/^\.//" > DEBIAN/conffiles
       cd - > /dev/null
       fakeroot dpkg --build $TMP . > $TMP.buildoutput
       result=$?
@@ -284,8 +324,8 @@ package_debian() {
       rm -rf $TMP $TMP.buildoutput
       if test $result -ne 0
       then
-         echo "Error while building package."
-         exit 1
+         output "Error while building package."
+         return 1
       fi
       grep "^${P_PKGNAME}_${B_ARCH}" $PKGLIST > /dev/null && sed -i "/^${P_PKGNAME}_${B_ARCH}/d" $PKGLIST
       echo -e "${P_PKGNAME}_${B_ARCH}\t$P_BUILDNR" >> $PKGLIST
@@ -294,8 +334,8 @@ package_debian() {
    else
       if test -f "$( echo $DESTDIR/$B_ARCH/${P_PKGDIR}/*.deb )" = "$DESTDIR/$B_ARCH/${P_PKGDIR}/*.deb"
       then
-         echo "Recipe indicates package should be in build dir, but it isn't."
-         exit 1
+         output "Recipe indicates package should be in build dir, but it isn't."
+         return 1
       else
          file="$DESTDIR/$B_ARCH/${P_PKGDIR}/*.deb"
          cp $file $PKGDIR
@@ -304,32 +344,31 @@ package_debian() {
    fi
    if test "${torepo,,}" = "y"
    then
+      output "Adding package to repo..."
       package_torepo $type $pkgfile
    else
-      echo $pkgfile
+      output $pkgfile
    fi
 }
 
 version_get() {
+   local pkg=$1
    export B_ARCH=$( arch_get )
    B_GITVER() {
       git ls-remote --tags $1 | grep -v '{}' | grep -v -e preview -e rc | cut -d '/' -f 3  | sed "s/^v//" | sort -t. -k 1,1n -k 2,2n -k 3,3n -k 4,4n | tail -1
    }
    export -f B_GITVER
-   CMD=$( recipe_section_get $RECIPE VERSION ) || exit 1
-   test $? -ne 0 && { echo $CMD ; exit 1; }
-   ver=$( bash $DEBUG -e -c "$CMD" )
-   test $? -ne 0 && { >&2 echo "Error while running version command for $NAME." ; exit 1 ; }
-   test "$ver" = "" && { >&2 echo "Version command returned no output." ; exit 1 ; }
+   CMD=$( recipe_section_get $pkg VERSION ) || return 1
+   test $? -ne 0 && { output $CMD ; return 1; }
+   ver=$( bash $DEBUG -e -c "$CMD" 2>/dev/null )
+   test $? -ne 0 && { >&2 output "Error while running version command for $pkg." ; return 1 ; }
+   test "$ver" = "" && { >&2 output "Version command for $pkg returned no output." ; return 1 ; }
    echo $ver
    return 0
 }
 
 parse_options() {
-   ACTION=
-   FORCE=0
-   QUIET=0
-   DEBUG=
+   ACTION= ; FORCE=0 ; QUIET=0 ; DEBUG= ; PKGS= ; FORCEVERSION=
    while test "$1" != ""
    do
       case $1 in
@@ -367,17 +406,16 @@ parse_options() {
          FORCEVERSION=$1
       ;;
       *)
-         NAME=$1
+         PKGS="$PKGS $1"
       ;;
       esac
       shift
    done
-   if test "$ACTION" != "" -a "$NAME" = ""
+   if test "$ACTION" != "autobuild" -a "$ACTION" != "" -a "$PKGS" = ""
    then
-      echo "No name specified."
+      output "No name specified."
       exit 1
    fi
-   RECIPE=$RECIPEDIR/$NAME.recipe
 }
 
 sanity_check() {
@@ -389,11 +427,37 @@ sanity_check() {
          missing="$missing $name"
       fi
    done
-   test "$missing" != "" && { echo "Missing required software to run script:$missing" ; exit 1;}
+   test "$missing" != "" && { output "Missing required software to run script:$missing" ; exit 1;}
+}
+
+output() {
+   test $QUIET -eq 1 && return
+   echo "$1"
+}
+
+check_new_version() {
+   local pkg=$1
+   local RET=0
+
+   version=$( version_get $pkg ) || return 1
+   if test "$FORCEVERSION" != ""
+   then
+      if test -d "$DESTDIR/$B_ARCH/$pkg-$FORCEVERSION"
+      then
+         output "Version $FORCEVERSION of $pkg is available"
+      else
+         output  "Version $FORCEVERSION of $pkg is not available"
+         RET=1
+      fi
+   else
+      test -d "$DESTDIR/$B_ARCH/$pkg-$version" && { output "No new version of $pkg is available (current $version)." ; RET=1 ;} || output "New version ($version) of $pkg is available"
+   fi
+   return $RET
 }
 
 main() {
-   #set -e
+   QUIET=0
+   declare -A packages_torepo
    test -f ~/.buildrc && . ~/.buildrc || { echo "No configuration file found."; exit 1;}
    sanity_check
    parse_options "$@"
@@ -401,35 +465,49 @@ main() {
 
    case $ACTION in
    "package")
-      package
+      for pkg in $PKGS
+      do
+         package $pkg
+      done
+      package_torepo_copy
    ;;
    "check")
-      version=$( version_get ) || exit 1
-      if test "$FORCEVERSION" != ""
-      then
-         if test -d "$DESTDIR/$B_ARCH/$NAME-$FORCEVERSION"
-         then
-            echo "Version $FORCEVERSION of $NAME is available"
-         else
-            echo "Version $FORCEVERSION of $NAME is not available"
-            exit 1
-         fi
-      else
-         test -d "$DESTDIR/$B_ARCH/$NAME-$version" && { echo "No new version of $NAME is available (current $version)." ; exit 1 ;}
-         echo "New version ($version) of $NAME is available"
-      fi
+      RET=0
+      for pkg in $PKGS
+      do
+         check_new_version $pkg || RET=1
+      done
+      exit $RET
    ;;
    "build")
-      version=$( version_get ) || exit 1
-      test "$FORCEVERSION" != "" && version=$FORCEVERSION
-      if test "$B_INSTANCE" != ""
-      then
-         ID=$NAME-$version-$B_INSTANCE
-      else
-         ID=$NAME-$version
-      fi
-      test -d "$DESTDIR/$B_ARCH/$ID" -a $FORCE -ne 1 && { echo "Version $version of $NAME is already built." ; exit 1 ;}
-      build $NAME $version
+      for pkg in $PKGS
+      do
+         version=$( version_get $pkg ) || exit 1
+         test "$FORCEVERSION" != "" && version=$FORCEVERSION
+         if test "$B_INSTANCE" != ""
+         then
+            ID=$pkg-$version-$B_INSTANCE
+         else
+            ID=$pkg-$version
+         fi
+         test -d "$DESTDIR/$B_ARCH/$ID" -a $FORCE -ne 1 && output "Version $version of $pkg is already built." || build $pkg $version
+      done
+   ;;
+   "autobuild")
+      for recipe in $RECIPEDIR/*.recipe
+      do
+         pkg=$( basename -s .recipe $recipe )
+         local info=$( recipe_section_get $pkg INFO opt )
+         autobuild=1
+         eval $( echo $info | grep "^autobuild=" )
+         if test $autobuild -eq 1 && test $FORCE -eq 1 || check_new_version $pkg > /dev/null
+         then
+            version=$( version_get $pkg ) || continue
+            build $pkg $version
+            test $? -ne 0 && echo "Autobuild $pkg version $version failed." || { echo "Autobuild $pkg version $version succeeded." ; package $pkg ; }
+         fi
+      done
+      package_torepo_copy
    ;;
    *)
       echo "No action specified, nothing to do."
